version: "3.8"
services:
  mongodb:  
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb-restapi-typescript-express:/data/db

    restart: unless-stopped

    

  node:
    image: "node"
    container_name: nodeapp

    depends_on:
      - mongodb

    working_dir: /usr/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/node/app
    
    command: "npm start"
    ports:
      - 1337:1337
    

volumes:
  mongodb-restapi-typescript-express:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24